---
title: "Biostatistics 234: Lab 2"
author: "Fernando Mora"
output: pdf_document
tables: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = '~/Documents/UCLA/Winter 2021/biostat234/lab 2/')
```

```{r, include=FALSE}
library(R2jags)
library(stringr)
library(memisc)
library(knitr)
library(kableExtra)
setwd("~/Documents/UCLA/Winter 2021/biostat234/lab 2/")
```

```{r, include=FALSE}
#setup code from JAGSLab2.R
#Plots excluded from this chunk

housing=read.table("housingdata2.txt")
housing   ## Always look at your data
## Anything funny about any of the columns?

#Give the columns useful names 
colnames(housing) <- c("cost", "eaves", "windows", "yard", "roof")

#SEPARATE X & Y
y<-housing[,1]
x<-as.matrix(housing[,2:5])

## Remember: look at your data.  

## Did you look at the recently defined x and y?  

#Create the model

reg = lm(y~x)
summary(reg) # classical regression
# There's a problem, what is it?
# Why is there a problem?

sink("housingmodel.txt")
cat("
model
{ 
   for(i in 1:N) {
	     y[i] ~ dnorm( mu[i] , tau )
	     mu[i] <- beta0 + inprod(x[i,] , beta[] )
		}
	      
	 beta0 ~ dnorm( mbeta0 , precbeta0)
	 
for (j in 1:K) {
	 beta[j] ~ dnorm( m[j] , prec[j] )
		}
	   tau ~ dgamma( tau.a , tau.b )
	   sigma <- 1 / sqrt( tau )
	}
  ",fill = TRUE)
sink()

# This copies the jags program to a file. Please take 
# the time to understand the model.

#DIFFERENT PRIORS TO TRY
dataA<-list(N=21, K=4, m=c(1.6053, 1.2556, 2.3413, 3.6771), 
prec=c(.2164, .1105, .2061, .1337), tau.a=17,
tau.b=1128, mbeta0= -5.682, precbeta0=.05464, x=x, y=y)

dataB<-list(N=21, K=4, m=c(1.6053, 1.2556, 2.3413, 3.6771), 
prec=c(.02774, .014160, .02642, .01714), tau.a=2.1795,
tau.b=144.6, mbeta0= -5.682, precbeta0=.007005, x=x, y=y)

dataC<-list(N=21, K=4, m=c(1.6053, 1.2556, 2.3413, 3.6771), 
prec=c(.005549, .002832, .005284, .003428), tau.a=.4359,
tau.b=28.92, mbeta0= -5.682, precbeta0=.00140, x=x, y=y)

#SET UP INITAL VALUES
# This creates a list with 5 copies of the initial values.
# Change the number 5 to match the n.chains variable in 
# the jags call.  

inits<-rep(list(list(beta0=0, beta=c(1,1,1,1),tau=1)),5)

#DEFINE PARAMETERS TO MONITOR
parameters <- c("beta0", "beta" , "tau")

#RUN THE JAGS PROGRAM, SAVING DATA TO LAB2.SIM
set.seed(1234)
lab2.sim <- jags (dataA, inits, parameters, "housingmodel.txt", n.chains=5, 
	n.iter=5100, n.burnin=100, n.thin=1, DIC=FALSE)

```

